### ISSUE TITLE
MacOSX with Bass?

### ISSUE THREAD

**Issue by godexsoft** [Hello-Meow/AudioImporter#1]
Is it possible to run BassImporter on mac? I get the following error at runtime:

```
DllNotFoundException: bass
Un4seen.Bass.Bass.InitBass ()
Un4seen.Bass.Bass..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Un4seen.Bass.Bass
BassImporter..cctor () (at Assets/AudioImporter/Scripts/BassImporter.cs:15)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for BassImporter
DecoderImporter.DoImport () (at Assets/AudioImporter/Scripts/DecoderImporter.cs:68)
UnityEngine.UnhandledExceptionHandler:<RegisterUECatcher>m__0(Object, UnhandledExceptionEventArgs)
DecoderImporter:DoImport() (at Assets/AudioImporter/Scripts/DecoderImporter.cs:97)
DecoderImporter:DoImport() (at Assets/AudioImporter/Scripts/DecoderImporter.cs:68)
```

I have placed libbass.dylib into the Plugins folder at the root of my project. I'm not sure if it is expected to work at all or it only would work with the Windows DLL and on Windows?

**Comment by Hello-Meow** [comment]
It might be possible. I'm not familiar with macOS, but I have tested it on Linux at some point by placing the platform specific library in a plugins folder.

Does fail both in the editor and in a standalone build? Does it help if you place the library in the project's root folder?

**Comment by godexsoft** [comment]
Actually, putting the library in the project's root folder just worked! Thanks o much for your help - i would not have thought to do that. Maybe worth updating the documentation to state that on MacOSX you need to put libbass.dylib (not a Bass.DLL) and into the root, not Plugins :)
Thanks!
