### ISSUE TITLE
Importer DLL issue with IL2CPP

### ISSUE THREAD

**Issue by ivanmotta** [Hello-Meow/AudioImporter#2]
Got errors building for Quest 2, on IL2CPP. Tested before with standard Android project and worked.
Tracked down to DLL error while building, and after deleting the NAudio.dll it worked normally as before.
Can it be updated?

**Comment by Hello-Meow** [comment]
Any unused importer can just be deleted. 

Ideally it would ignore unused importers. After some testing ENABLE_IL2CPP seems to work for this. I'll add it to my todo list.
